list: $/vanopstal/pannes/models/panne/columns.yaml
modelClass: Vanopstal\Pannes\Models\Panne
title: Pannes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'vanopstal/pannes/pannes/update/:id'
